
server:
  servlet:
    context-path: /sso-auth-server
  port: 8081

# Embedded Spring LDAP
spring:
  ldap:
    embedded:
      base-dn: dc=memorynotfound,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:schema.ldif
      port: 12345
      enabled: false
logging:
  level:
    org: INFO
##security.oauth2.client.client-id=bael-client
##security.oauth2.client.client-secret=bael-secret

### Only for academic purposes, these endpoints shouldn't be unsecured
security:
  oauth2:
    authorization:
      check-token-access: permitAll()
      token-key-access: permitAll()
    resource:
      jwk:
        key-set-uri: http://localhost:8081/sso-auth-server/.well-known/jwks.json

ldap:
    uri: {ldapuri}

jwt:
  CLIENT_ID: {CLIENT_ID}
  SECRET_KEY: {SECRET_KEY}
  KEY_STORE_FILE: pfcti.jks #-keystore
  KEY_STORE_PASSWORD: {KEY_STORE_PASSWORD} #-storepass
  KEY_ALIAS: pfcti-jwt
  JWK_KID: {JWK_KID} #-keypass

